### ISSUE TITLE
[ Bug Report ] Identifier field

### ISSUE THREAD

**Issue by kevzak** [keyko-io/filecoin-verifier-frontend#766] opened 2023-05-23 14:34 UTC
**Describe the bug**
In the new application, for E-Fil, there is no identifier field anymore and its giving me issues to trigger the initial allocation 

As a side note: I think the identifier field was removed on purpose because it was not a client facing field. Can the identifier be updated someplace else now?

**To Reproduce**
1. Go to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1559504820

**Expected behavior**
without efil Identifier I cannot trigger this application

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fabriziogianni7** [comment] 2023-05-29 06:58
I made a PR to restore the issue template as it was before . maybe @panges2 can create a task on notion and assign it to me to make this feat?

**Comment by fabriziogianni7** [comment] 2023-05-31 09:01
closing this as it's not a bug

**Closed by fabriziogianni7** 2023-05-31 09:01 UTC
Labels: bug
